console.log('Hello World!');
console.log(123);
console.log(true);
console.log({a:123, b:3});
console.table({a:123, b:3});
console.error({a:123, b:3});
console.warn({a:123, b:3});
console.time('Hello');
  console.table({a:123, b:3});
  console.error({a:123, b:3});
  console.warn({a:123, b:3});
console.timeEnd('Hello');
